name:                carcassonne-server
version:             0.1.0.0
github:              "rostislavlitovkin/carcassonne/carcassonne-server"
license:             BSD-3-Clause
author:              "Rostislav Litovkin"
maintainer:          "litovros@fit.cvut.cz"
copyright:           "2025 Rostislav Litovkin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rostislavlitovkin/carcassonne#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- lens
- monad-logger
- mtl
- persistent
- persistent-sqlite
- persistent-template
- servant
- servant-server
- servant-swagger
- servant-swagger-ui
- swagger2
- text
- time
- uuid
- warp
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  carcassonne-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - carcassonne-server

tests:
  carcassonne-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - carcassonne-server
