module Evergreen.Migrate.V3 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Types
import Evergreen.V3.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V3.Types.FrontendModel Evergreen.V3.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V3.Types.BackendModel Evergreen.V3.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V3.Types.FrontendMsg Evergreen.V3.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V3.Types.ToBackend Evergreen.V3.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V3.Types.BackendMsg Evergreen.V3.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V3.Types.ToFrontend Evergreen.V3.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V3.Types.BackendModel
migrate_Types_BackendModel old =
    case old of
        Evergreen.V1.Types.BePlayerRegistration p0 ->
            Evergreen.V3.Types.BePlayerRegistration p0

        notices ->
            {- @NOTICE `BeGamePlayed {}` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V3.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V1.Types.FePlayerRegistration p0 ->
            Evergreen.V3.Types.FePlayerRegistration p0

        Evergreen.V1.Types.FeLobby p0 ->
            Evergreen.V3.Types.FeLobby p0

        notices ->
            {- @NOTICE `FeGamePlayed {}` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V3.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.NameInputChanged p0 ->
            Evergreen.V3.Types.NameInputChanged p0

        Evergreen.V1.Types.Register ->
            Evergreen.V3.Types.Register

        Evergreen.V1.Types.Kick p0 ->
            Evergreen.V3.Types.Kick p0

        Evergreen.V1.Types.ClearError ->
            Evergreen.V3.Types.ClearError

        Evergreen.V1.Types.FNoop ->
            Evergreen.V3.Types.FNoop

        notices ->
            {- @NOTICE `FeInitializeGame` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `FeRotateTileLeft` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `FePlaceTile Evergreen.V3.Types.Game.Coordinate` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V3.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.RegisterPlayer p0 ->
            Evergreen.V3.Types.RegisterPlayer p0

        Evergreen.V1.Types.KickPlayer p0 ->
            Evergreen.V3.Types.KickPlayer p0

        notices ->
            {- @NOTICE `InitializeGame` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `RotateTileLeft` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `PlaceTile Evergreen.V3.Types.Game.Coordinate` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V3.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.PlayerRegistrationUpdated p0 ->
            Evergreen.V3.Types.PlayerRegistrationUpdated p0

        Evergreen.V1.Types.PlayerKicked p0 ->
            Evergreen.V3.Types.PlayerKicked p0

        notices ->
            {- @NOTICE `GameInitialized {}` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            {- @NOTICE `UpdateGameState {}` was added in V3.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})
